export { default as RegisterPage } from "./RegisterPage/RegisterPage";
export { default as Question } from "./Question/Question";
export { default as Contact } from "./Contact/Contact";
export { default as Reserva } from "./Reserva/Reserva";
export { default as ErrorPage } from "./Error/Error";
export { default as Login } from "./Login/Login";
export { default as Home } from "./Home/Home";
export { default as Perfil } from "./Perfil/Perfil";
export { default as Search } from "./Search/Serach"